task done
Rommelua/cinema pull request #4
Opened 2020-10-08 20:19 UTC by Rommelua

2020-10-08 21:00 UTC, DariiaPikul approved these changes
Well done!

2020-10-08 21:00 UTC, dariiabutorina commented on src/main/java/com/dev/cinema/service/impl/ShoppingCartServiceImpl.java
> +        shoppingCart.getTickets().add(ticket);
```suggestion
        ShoppingCart shoppingCart = getByUser(user);
        shoppingCart.getTickets().add(new Ticket(user, movieSession));
```

2020-10-08 22:19 UTC, DariiaPikul requested changes

2020-10-08 22:19 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/Main.java
> +        cartService.registerNewShoppingCart(alisa);
How about registering a new cart at the moment of a user registering?

2020-10-09 07:47 UTC, Sofasmile commented on src/main/java/com/dev/cinema/Main.java
> +        cartService.registerNewShoppingCart(alisa);
погоджуюсь з @DariiaPikul варто перенести registerNewShoppingCart до register() метода

2020-10-09 07:47 UTC, Sofasmile commented on src/main/java/com/dev/cinema/service/impl/ShoppingCartServiceImpl.java
> +        Ticket ticket = new Ticket(user, movieSession);
я так розумію що за збереження білета в БД відповідають каскади в shopping cart?

2020-10-09 08:16 UTC, Rommelua commented on src/main/java/com/dev/cinema/service/impl/ShoppingCartServiceImpl.java
> +        Ticket ticket = new Ticket(user, movieSession);
Именно так, на данном этапе ticketDao использовать смысла не вижу, Hibernate все сам делает :) Если бы в задании не было прописано, то я бы ticketDao и не создавал.

2020-10-09 08:21 UTC, Rommelua commented on src/main/java/com/dev/cinema/Main.java
> +        cartService.registerNewShoppingCart(alisa);
Я тоже с вами полностью согласен! Но тогда вопрос: когда я в прошлом проэкте создавал корзину в сервисе для нового юзера, то эту идею зарубили, мотивируя тем, что админам не нужна корзина))) Хотя как по мне она особо есть не просит, а отсутствие корзины - потенциальный NPE. Почему теперь стало можно?

2020-10-09 08:27 UTC, Rommelua commented on src/main/java/com/dev/cinema/service/impl/ShoppingCartServiceImpl.java
> +        shoppingCart.getTickets().add(ticket);
Можно, конечно - на 1 строчку меньше, но немного затрудняет чтение мне кажется, так что оставлю как есть.

2020-10-09 08:46 UTC, Sofasmile commented on src/main/java/com/dev/cinema/Main.java
> +        cartService.registerNewShoppingCart(alisa);
тепер ми юзера створює через AuthenticationService -> register() тут буде корзина + роль присвоюватись
а адміна будемо створювати через UserService -> create() тут не буде ні корзини ні ролі

2020-10-09 08:47 UTC, Sofasmile commented on src/main/java/com/dev/cinema/Main.java
> +        cartService.registerNewShoppingCart(alisa);
а в попередньому проекті в нас був лише один метод на рівні сервісу, тому ми тоді там не створювали корзину а створювали на рівні контроллера

2020-10-09 08:51 UTC, Sofasmile approved these changes

2020-10-09 10:36 UTC, merged